<p>
    <?php
        if ($block->haveConfigAccess())
        {
            echo __('Enter your XKey in your store configuration and click this button.');
        }
        else
        {
            echo __('Please contact your administrator about this problem.');
        }
    ?>
</p>
<br>
<form action="<?php echo $block->getAuthUrl(); ?>">
    <button class="primary" type="submit"><?php echo __('Authenticate') ?></button>
</form>
