<?php

echo '<h1>Fields :</h1>';

$json = $block->get('fields/');

$tab = json_decode($json, TRUE);

for ($i = 0; $i < count($tab); $i = $i + 1)
{
  echo '<p>id = ' . $tab[$i]['id'] . ' | name = ' . $tab[$i]['name'] . ' | unicity = ' . $tab[$i]['isUnicity'] . '</p>';
  $block->addChangeFields($tab[$i]['id'], $tab[$i]['name'], $tab[$i]['isUnicity']);
}

echo '<br>';

echo '<h1>Segments :</h1>';

$json = $block->get('segments/');

$tab = json_decode($json, TRUE);

for ($i = 0; $i < count($tab); $i = $i + 1)
{
  echo '<p>id = ' . $tab[$i]['id'] . ' | name = ' . $tab[$i]['name'] . '</p>';
  $block->addChangeSegments($tab[$i]['id'], $tab[$i]['name']);
}

?>
