<!--
/**
 * Copyright © 2015 NP6. All rights reserved.
 * See LICENSE.txt for license details.
 */
 -->
<?php

echo '<h1>Fields :</h1>';

$json = $block->get('fields/');

$tab = json_decode($json, TRUE);

for ($i = 0; $i < count($tab); $i = $i + 1)
{
  $block->addChangeFields($tab[$i]['id'], $tab[$i]['name'], $tab[$i]['isUnicity']);
  $tab_2 = $block->getFields($tab[$i]['id']);
  echo '<p>id = ' . $tab_2['id'] . ' | name = ' . $tab_2['name'] . ' | unicity = ' . $tab_2['isUnicity'] . '</p>';
}

echo '<br>';

//$block->flushFields();

$tab = $block->getAllFields();

foreach ($tab as $tab_2)
{
    echo '<p>FOREACH : id = ' . $tab_2['id'] . ' | name = ' . $tab_2['name'] . ' | unicity = ' . $tab_2['isUnicity'] . '</p>';
}

echo '<br>';

echo '<h1>Segments :</h1>';

$json = $block->get('segments/');

$tab = json_decode($json, TRUE);

for ($i = 0; $i < count($tab); $i = $i + 1)
{
  $block->addChangeSegments($tab[$i]['id'], $tab[$i]['name']);
  $tab_2 = $block->getSegments($tab[$i]['id']);
  echo '<p>id = ' . $tab_2['id'] . ' | name = ' . $tab_2['name'] . '</p>';
}

echo '<br>';

//$block->flushSegments();

$tab = $block->getAllSegments();

foreach ($tab as $tab_2)
{
    echo '<p>FOREACH : id = ' . $tab_2['id'] . ' | name = ' . $tab_2['name'] . '</p>';
}

echo '<br>';
echo '<br>';

echo '<p>' . json_encode($block->getDataFromSqlToFields('2')) . '</p>';

echo '<br>';
echo '<br>';

?>
