<div class="admin__page-nav">
    <?php if ($block->navTitle): ?>
        <div class="admin__page-nav-title">
            <strong><?php echo $block->navTitle; ?></strong>
        </div>
    <?php endif ?>
    <div id="tabs">
        <ul>
            <?php var_dump($block->tabName); var_dump($block->tabAmmount);
                foreach($block->tabName as $tab)
                {
                    echo '<li class="admin__page-nav-item"><a href="#tabs-' . $tab['content'] . '">' . $tab['name'] . '</a></i>';
                }
            ?>
        </ul>
    </div>
</div>

<script>
require(['jquery',"mage/backend/tabs"], function($){
    $(function() {
        $('#tabs').tabs({
            active: '<?php echo $block->tabName[0]['name'] ?>',
            destination: '#<?php echo $block->tabName[0]['content'] ?>',
            shadowTabs: null,
            tabsBlockPrefix: '',
            tabIdArgument: 'active_tab'
    });
});
</script>
