<!--
/**
 * Copyright © 2015 NP6. All rights reserved.
 * See LICENSE.txt for license details.
 */
 -->
<div>
    <div class="admin__page-section-title">
        <span class="title">Actions</span>
    </div>
    <div>
        <p>
            <a href="<?php echo $block->getReloadUrl(); ?>">
                <button class="primary" type="button"><?php echo __('Reload')?></button>
            </a>
        </p>
    </div>
</div>
