<div>
    <div class="admin__page-section-title">
        <span class="title">Actions</span>
    </div>
    <div>
        <p>
            <a href="<?php echo $block->getReloadUrl(); ?>">
                <button class="primary" type="submit"><?php __('Reload'); ?></button>
            </a>
        </p>
        <p>
            <a href="<?php echo $block->getDevUrl(); ?>">
                <button class="primary" type="submit">Dev</button>
            </a>
        </p>
    </div>
</div>
