<div>
    <div class="admin__page-section-title">
        <span class="title">Actions</span>
    </div>
    <div>
        <?php if (!$block->isReady()): ?>
            <form action="/admin/MailPerformance/Settings/Authenticate">
                <button class="primary" type="submit">Authenticate</button>
            </form>
        <?php else: ?>
            <button class="primary ui-corner-all" type="button">Reload MailPerformance components</button>
        <?php endif; ?>
    </div>
</div>
