<div class="row">
    <div class="col-m-3">
        <div class="admin__page-section-title">
            <span class="title">Account Informations</span>
        </div>
        <table class="admin__table-secondary">
            <tbody>
                <tr>
                    <th>Name</th>
                    <td>ACC_NAME</td>
                </tr>
                <tr>
                    <th>Owner</th>
                    <td>ACC_OWNER</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>ACC_EMAIL</td>
                </tr>
                <tr>
                    <th>Expiration date</th>
                    <td>ACC_DATE</td>
                </tr>
                <tr>
                    <th>XKey</th>
                    <td>input</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
