<div>
    <div class="admin__page-section-title">
        <span class="title"><?php echo __("Account Informations") ?></span>
    </div>
    <?php
        if ($block->isInfoAllowed()):
            $infos = $block->getInfos();
    ?>
    <table class="admin__table-secondary">
        <tbody>
        <?php if ($block->isAllowed('AccName')): ?>
            <tr>
                <th><?php echo __('Name') ?></th>
                <td><?php echo $infos['ACC_NAME']?></td>
            </tr>
        <?php endif; if ($block->isAllowed('AccOwner')): ?>
            <tr>
                <th><?php echo __("Owner") ?></th>
                <td><?php echo $infos['ACC_OWNER']?></td>
            </tr>
        <?php endif; if ($block->isAllowed('AccEmail')): ?>
            <tr>
                <th><?php echo __("Email") ?></th>
                <td><?php echo $infos['ACC_EMAIL']?></td>
            </tr>
        <?php endif; if ($block->isAllowed('AccExpiration')): ?>
            <tr>
                <th><?php echo __("Expiration date") ?></th>
                <td><?php echo $infos['ACC_DATE']?></td>
            </tr>
        <?php endif; if ($block->isAllowed('AccXKey')): ?>
            <tr>
                <th>XKey</th>
                <td>
                    <input type="text" value="<?php echo $infos['ACC_XKEY'] ?>" readonly>
                </td>
            </tr>
        <?php endif; ?>
            <tr>
                <th><?php echo __('Auto add subscriber') ?></th>
                <td>
                    <?php echo $block->isFeatureEnabled('auto_add_subscriber'); ?>
                </td>
            </tr>
            <tr>
                <th><?php echo __('Cart Abandon') ?></th>
                <td>
                    <?php echo $block->isFeatureEnabled('cart_abandon'); ?>
                </td>
            </tr>
        </tbody>
    </table>
    <?php else: ?>
    <p><?php echo __('You don\'t have access to this. If you believe this is an error, please contact your Administrator.') ?></p>
    <?php endif; ?>
</div>
