<div>
    <div class="admin__page-section-title">
        <span class="title">Account Informations</span>
    </div>
    <?php
        if ($block->isInfoAllowed()):
            $infos = $block->getInfos();
    ?>
    <table class="admin__table-secondary">
        <tbody>
        <?php if ($block->isAllowed('AccName')): ?>
            <tr>
                <th>Name</th>
                <td><?php echo $infos['ACC_NAME']?></td>
            </tr>
        <?php endif; if ($block->isAllowed('AccOwner')): ?>
            <tr>
                <th>Owner</th>
                <td><?php echo $infos['ACC_OWNER']?></td>
            </tr>
        <?php endif; if ($block->isAllowed('AccEmail')): ?>
            <tr>
                <th>Email</th>
                <td><?php echo $infos['ACC_EMAIL']?></td>
            </tr>
        <?php endif; if ($block->isAllowed('AccExpiration')): ?>
            <tr>
                <th>Expiration date</th>
                <td><?php echo $infos['ACC_DATE']?></td>
            </tr>
        <?php endif; if ($block->isAllowed('AccXKey')): ?>
            <tr>
                <th>XKey</th>
                <td>
                    <input type="text" value="<?php echo $infos['ACC_XKEY'] ?>" readonly>
                </td>
            </tr>
        <?php endif; ?>
            <tr>
                <th>Auto add subscriber</th>
                <td>
                    <?php echo $block->isFeatureEnabled('auto_add_subscriber'); ?>
                </td>
            </tr>
            <tr>
                <th>Cart Abandon</th>
                <td>
                    <?php echo $block->isFeatureEnabled('cart_abandon'); ?>
                </td>
            </tr>
        </tbody>
    </table>
    <?php else: ?>
    <p>You don't have access to this. If you believe this is an error, please contact your Administrator.</p>
    <?php endif; ?>
</div>
